/**
 * Attract-Mode Frontend
 *
 * @package Signal
 * @global
 */

// -------------------------------------------------------------------------------------

local signalActions = [
    "back",
	"up",
	"down",
	"left",
	"right",
	"select",
	"prev_game",
	"next_game",
	"prev_page",
	"next_page",
	"prev_letter",
	"next_letter",
	"prev_favourite",
	"next_favourite",
	"prev_filter",
	"next_filter",
	"prev_display",
	"next_display",
	"random_game",
	"replay_last_game",
	"filters_menu",
	"displays_menu",
	"add_tags",
	"add_favourite",
	"configure",
	"layout_options",
	"plugin_options",
	"toggle_layout",
	"reload_layout",
	"reload_config",
	"reset_window",
	"exit",
	"exit_to_desktop",
	"toggle_fullscreen",
	"toggle_movie",
	"toggle_mute",
	"toggle_rotate_left",
	"toggle_rotate_right",
	"toggle_flip",
	"intro",
	"screen_saver",
	"screenshot",
	"insert_game",
	"edit_game",
	"custom1",
	"custom2",
	"custom3",
	"custom4",
	"custom5",
	"custom6",
	"custom7",
	"custom8",
	"custom9",
	"custom10"
];
