import { builders } from "prettier/doc";

const {
    addAlignmentToDoc,
    align,
    breakParent,
    conditionalGroup,
    cursor,
    dedent,
    dedentToRoot,
    fill,
    group,
    hardline,
    hardlineWithoutBreakParent,
    ifBreak,
    indent,
    indentIfBreak,
    join,
    label,
    line,
    lineSuffix,
    lineSuffixBoundary,
    literalline,
    literallineWithoutBreakParent,
    markAsRoot,
    softline,
    trim,
} = builders;

export {
    addAlignmentToDoc,
    align,
    breakParent,
    conditionalGroup,
    cursor,
    dedent,
    dedentToRoot,
    fill,
    group,
    hardline,
    hardlineWithoutBreakParent,
    ifBreak,
    indent,
    indentIfBreak,
    join,
    label,
    line,
    lineSuffix,
    lineSuffixBoundary,
    literalline,
    literallineWithoutBreakParent,
    markAsRoot,
    softline,
    trim,
};
